export const PET_SKILL_IDS = {
  transmuteMetal: 'pet_transmute_metal',
  woodHeal: 'pet_wood_heal',
  woodVolley: 'pet_wood_volley',
  waterShield: 'pet_water_shield',
  waterPierce: 'pet_water_pierce',
  fireBurst: 'pet_fire_burst',
  fireBoost: 'pet_fire_boost',
  earthShield: 'pet_earth_shield',
  earthHeartConvert: 'pet_earth_heart_convert',
  // ── 阶段八新增（展示 dot / stun / defenseBreak / multiHit / convertShape）──
  fireDot: 'pet_fire_dot',
  fireDotUr: 'pet_fire_dot_ur',
  metalDefBreak: 'pet_metal_def_break',
  metalMultiHit: 'pet_metal_multi_hit',
  waterStun: 'pet_water_stun',
  waterMultiHit: 'pet_water_multi_hit',
  woodMultiHit: 'pet_wood_multi_hit',
  woodBigHeal: 'pet_wood_big_heal',
  earthConvertRow: 'pet_earth_convert_row',
  // ── 目标十三：技能唯一化（消灭复用，30 宠 30 独占技） ──
  thunderCrit: 'pet_thunder_crit',
  shadowPurify: 'pet_shadow_purify',
  starCross: 'pet_star_cross',
  chaosHaste: 'pet_chaos_haste',
  abyssDelay: 'pet_abyss_delay',
  voidResonance: 'pet_void_resonance',
  skyfallGravity: 'pet_skyfall_gravity',
  riftShield: 'pet_rift_shield',
  earthTime: 'pet_earth_time',
  frostGuard: 'pet_frost_guard',
  goldenCleanse: 'pet_golden_cleanse',
  abyssBulwark: 'pet_abyss_bulwark',
} as const;

export const ENEMY_SKILL_IDS = {
  golemGuard: 'enemy_golem_guard',
  serpentHeal: 'enemy_serpent_heal',
  bladeCharge: 'enemy_blade_charge',
  lionCharge: 'enemy_lion_charge',
  pandaGuard: 'enemy_panda_guard',
  pandaHeal: 'enemy_panda_heal',
  // ── 目标十三：新敌人技能池（章节机制载体） ──
  sealOrbs: 'enemy_seal_orbs',
  poisonTeam: 'enemy_poison_team',
  timeSqueeze: 'enemy_time_squeeze',
  healBlock: 'enemy_heal_block',
  enrage: 'enemy_enrage',
  skillSeal: 'enemy_skill_seal',
  // ── 后期章节（9~16）梯度变体：同机制加压，让复用的杂怪在高章节换一副面孔 ──
  sealOrbsHeavy: 'enemy_seal_orbs_heavy',
  poisonTeamHeavy: 'enemy_poison_team_heavy',
  timeSqueezeHeavy: 'enemy_time_squeeze_heavy',
  healBlockHeavy: 'enemy_heal_block_heavy',
  skillSealHeavy: 'enemy_skill_seal_heavy',
  golemGuardHeavy: 'enemy_golem_guard_heavy',
  serpentHealHeavy: 'enemy_serpent_heal_heavy',
  chargeHeavy: 'enemy_charge_heavy',
  enrageHeavy: 'enemy_enrage_heavy',
  // ── 新机制：削攻与免控 ──
  atkDebuff: 'enemy_atk_debuff',
  atkDebuffHeavy: 'enemy_atk_debuff_heavy',
  resolve: 'enemy_resolve',
  elementAbsorb: 'enemy_element_absorb',
  counterStrike: 'enemy_counter_strike',
  // ── 硬闸门：三档梯度（轻/常规/首领），按章逐级加压 ──
  elementGateLight: 'enemy_element_gate_light',
  elementGate: 'enemy_element_gate',
  elementGateBoss: 'enemy_element_gate_boss',
  comboGateLight: 'enemy_combo_gate_light',
  comboGate: 'enemy_combo_gate',
  comboGateBoss: 'enemy_combo_gate_boss',
  damageVoid: 'enemy_damage_void',
  undying: 'enemy_undying',
  counterSeal: 'enemy_counter_seal',
} as const;
